// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVtVR8vFlewpiUWT2koSed8XPkJWdotbA',
    appId: '1:304070513794:web:a86ce2e103a6143163909b',
    messagingSenderId: '304070513794',
    projectId: 'flutter-first-project-1a6b9',
    authDomain: 'flutter-first-project-1a6b9.firebaseapp.com',
    storageBucket: 'flutter-first-project-1a6b9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2vLJAMUDTA71X78kiXYvILOtyShhkWJI',
    appId: '1:304070513794:android:e2c16a2a44fc2f5a63909b',
    messagingSenderId: '304070513794',
    projectId: 'flutter-first-project-1a6b9',
    storageBucket: 'flutter-first-project-1a6b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdKnJeG1XyMw8ySATGjemaar3qi8XG_xM',
    appId: '1:304070513794:ios:d87264a2656a6fd363909b',
    messagingSenderId: '304070513794',
    projectId: 'flutter-first-project-1a6b9',
    storageBucket: 'flutter-first-project-1a6b9.appspot.com',
    iosBundleId: 'com.example.class22a',
  );
}
